/*
 * File: app/view/BusinessList.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CitySearch.view.BusinessList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.businesslist',

    requires: [
        'Ext.XTemplate'
    ],

    config: {
        itemId: 'mylist6',
        store: 'Hotels',
        itemTpl: [
            '<img class="photo" ',
            '     src="{photo_url}"',
            '     align="left" style="width: 40px; height: 40px; margin-right: 5px"/> ',
            '{name}<br/>',
            '<img src="{rating_img_url_small}"/>&nbsp;',
            '<small>{address1}</small>'
        ]
    }

});