/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CitySearch.view.Main', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.main',

    requires: [
        'CitySearch.view.BusinessList',
        'Ext.dataview.List',
        'Ext.tab.Bar',
        'Ext.field.Search'
    ],

    config: {
        layout: {
            type: 'card',
            animation: 'flip'
        },
        items: [
            {
                xtype: 'businesslist',
                title: 'Hotels',
                iconCls: 'home'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                layout: {
                    type: 'hbox',
                    pack: 'center'
                },
                items: [
                    {
                        xtype: 'searchfield',
                        flex: 1,
                        itemId: 'searchfield',
                        value: 'Washington, DC',
                        placeHolder: 'Search'
                    }
                ]
            },
            {
                xtype: 'businesslist',
                store: 'Restaurants',
                title: 'Restaurants',
                iconCls: 'favorites'
            },
            {
                xtype: 'businesslist',
                store: 'Shops',
                title: 'Shopping',
                iconCls: 'time'
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});